### ISSUE TITLE
Minas para los Staff Mod y Helper

### ISSUE THREAD

**Issue by xXIDontKnowXx** [esquerbatua/DestinyumCraft#20]
Esto consiste que hagan una mina privada para los staff, por ej: que en la mina Helper, den lo mismo que en la DC master con el autoblock

**Comment by esquerbatua** [comment]
Ni de coña vamos a hacer eso xD los rangos del staff son completamente voluntarios y no deberían tener mas ventajas que los jugadores, al menos desde mi punto de vista.
